# Generated by Django 3.2.22 on 2023-10-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='example',
            fields=[
                ('exampleID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exampleName', models.CharField(max_length=255)),
                ('inputFile', models.FileField(upload_to='example_files/')),
                ('maxIteration', models.IntegerField()),
                ('maxTime', models.TimeField()),
                ('description', models.TextField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('date', models.DateField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('modelID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('principal', models.CharField(max_length=255)),
                ('advanced', models.BooleanField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='model_run',
            fields=[
                ('runID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('outputFile', models.FileField(upload_to='output_model_run/')),
                ('date', models.DateField()),
                ('isActive', models.BooleanField()),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.model')),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('problemID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('problemName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.BinaryField(blank=True, null=True)),
                ('image2', models.BinaryField(blank=True, null=True)),
                ('image3', models.BinaryField(blank=True, null=True)),
                ('principles', models.TextField()),
                ('dataDescription', models.TextField()),
                ('parameterDescription', models.TextField()),
                ('programDescription', models.TextField()),
                ('solutionDescription', models.TextField()),
                ('codePython', models.TextField()),
                ('codeC', models.TextField()),
                ('codeJava', models.TextField()),
                ('date', models.DateField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='solver',
            fields=[
                ('solverID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('solverName', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('strengths', models.TextField(max_length=255)),
                ('applications', models.TextField(max_length=255)),
                ('referencesURL', models.URLField(max_length=255)),
                ('date', models.DateField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='default_param',
            fields=[
                ('solverID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.solver')),
                ('paramName', models.TextField(max_length=255)),
                ('disValue', models.TextField(max_length=255)),
                ('conValue', models.TextField(max_length=255)),
                ('editable', models.BooleanField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='param_run',
            fields=[
                ('runID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.model_run')),
                ('param', models.JSONField()),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='model_solver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.model')),
                ('solverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.solver')),
            ],
        ),
        migrations.AddField(
            model_name='model_run',
            name='solverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.solver'),
        ),
        migrations.AddField(
            model_name='model',
            name='problemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.problem'),
        ),
        migrations.CreateModel(
            name='example_run',
            fields=[
                ('runID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('runDateTime', models.DateTimeField(auto_now_add=True)),
                ('runStatus', models.CharField(choices=[('completed', 'Hoàn thành'), ('incomplete', 'Chưa hoàn thành'), ('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('error', 'Lỗi'), ('success', 'Thành công')], max_length=20)),
                ('paramList', models.JSONField()),
                ('exampleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.example')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='modelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.model'),
        ),
    ]
